name: CI
on:
  push:
    branches:
      - main
    paths:
      - "README.md"
      - "helm/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go 1.22.5
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.5

      - name: Build
        run: go build -o go-web-app

      - name: Test
        run: go test ./...

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1
      - name: Lint
        run: golangci-lint run
